name: notelike_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  io: ^0.3.3
  image_picker: ^0.5.0
  cupertino_icons: ^0.1.2
  firebase_analytics: ^0.3.3
  firebase_auth: ^0.6.6
  google_sign_in: ^3.2.4
  firebase_database: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  


flutter:
  uses-material-design: true

  assets:
    - assets/0.png
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/5.png
    - assets/6.png
    - assets/7.png
    - assets/8.png
    - assets/9.png
    - assets/10.png
    - assets/comment.png
    - assets/image.png
    - assets/movie.png
    - assets/music.png
    - assets/text.png


